apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-server
  template:
    metadata:
      labels:
        app: http-server
    spec:
      containers:
      - name: http-server
        image: whpskg/6446-app:latest
        ports:
        - containerPort: 5678
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "512Mi" # Maximum amount of memory the container can use
            cpu: "500m"     # Maximum amount of CPU the container can use (0.5 CPU)