apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: http-server
  minReplicas: 1
  maxReplicas: 30
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 5
      policies:
      - type: Pods
        value: 1
        periodSeconds: 1
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 5
      policies:
      - type: Pods
        value: 1
        periodSeconds: 1
      selectPolicy: Max